---
date: "2018-09-08T00:00:00+02:00"
draft: false
linktitle: Uitslagen
menu:
  statistieken:
    parent: Per Wedstrijd
    weight: 1
title: Uitslagen
toc: false
type: docs
---

```{r rLoadLibraries, echo=FALSE, results='hide',echo=FALSE,warning=FALSE,message=FALSE}
library(DT)
library(tidyverse)
library(htmlwidgets)
library(htmltools)
library(widgetframe)
load(file = "c:/DATA/MEGABIKE/WEBSITE/CODE/RMegabikeAlles.RData")
Koers<-D_Koersen%>%filter(TEVERWERKEN==TRUE)%>%mutate(KNAAM=as.character(KNAAM))%>%select(JAAR,KCODE,KNAAM,KOERSDATUM)
R_PuntenPerKoers<-D_KoersenPuntenDeelnemers%>%rename(Koers=KNAAM,Score=PUNTEN,Plaats=PLAATS,Restbudget=RESTBUDGET,Naam=NAAM,Jaar=JAAR)%>%select(Jaar,Koers,Naam,Plaats,Score,Restbudget)
R_PuntenPerKoers$Jaar<-as.factor(as.character(R_PuntenPerKoers$Jaar))
R_PuntenPerKoers$Koers<-as.factor(as.character(R_PuntenPerKoers$Koers))
ZoekKolommen <- vector("list", 6) 
ZoekKolommen[[1]]<-list(search=paste('["',Koers[1,"JAAR"],'"]',sep=''))
ZoekKolommen[[2]]<-list(search=paste('["',Koers[1,"KNAAM"],'"]',sep=''))
 d1<-datatable(
   R_PuntenPerKoers,rownames = FALSE, filter = list(position = 'top', clear = FALSE)
 ,options = list(pageLength = 70, searchCols = ZoekKolommen ))
```

```{r resultaaat,results='asis',echo=FALSE,warning=FALSE,message=FALSE}
frameWidget(d1,height = 10000)
```
