---
author: de megabike organisatie
type: post
date: 2019-03-02
categories:
  - Verslagen
params:
  ParamBlogId: "OHN2019"
title: "Omloop Het Nieuwsblad 2019"
url: "Omloop-Het-Nieuwsblad-2019"
output: html_document
---
## Verslag

```{r rLoadLibraries, echo=FALSE, results='hide',echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(pander)
load(file = "d:/DATA/RMEGABIKE/CODESITE/CODE/RMegabikeAlles.RData")
PanderTableDataPuntenKoers<-D_KoersenPuntenDeelnemers%>%rename(Koers=KNAAM,Score=PUNTEN,Plaats=PLAATS,Restbudget=RESTBUDGET,Naam=NAAM,Jaar=JAAR)%>%filter(BLOGID==params$ParamBlogId)%>% select(Naam,Plaats,Score,Restbudget)%>%arrange((Plaats))

PanderTableDataTussenstandKoers<-D_KoersenPuntenDeelnemers%>%rename(Koers=KNAAM,Tussenstand=TUSSENSTAND,Plaats=TUSSENPLAATS,Restbudget=RESTBUDGET,Naam=NAAM,Jaar=JAAR)%>%filter(BLOGID==params$ParamBlogId)%>% select(Naam,Plaats,Tussenstand,Restbudget)%>%arrange((Plaats))

PanderTableDataOptimalePloeg<-D_KoersenOptimalePloeg%>%rename(Koers=KNAAM,Score=SCORE,Kost=RPUNTEN,Naam=RNAAM,Jaar=JAAR)%>%filter(BLOGID==params$ParamBlogId)%>% select(Naam,Score,Kost)%>%arrange(desc(Score))

Verslag<-D_Verslagen%>%filter(BLOGID==params$ParamBlogId)%>%select(VERSLAG)
Verslag<-Verslag[1,1]
Verslag<-as.character(Verslag)
```


```{r resVerslag, echo=FALSE, results='asis',warning=FALSE}
cat(Verslag)
```

## Uitslag

```{r resUitslag, echo=FALSE, results='asis',warning=FALSE}
pandoc.table(PanderTableDataPuntenKoers)
```

## Tussenstand

```{r resTussenstand, echo=FALSE, results='asis',warning=FALSE}
pandoc.table(PanderTableDataTussenstandKoers)
```


## Optimale ploeg

```{r resOptimale, echo=FALSE, results='asis',warning=FALSE}
pandoc.table(PanderTableDataOptimalePloeg)
```



