
---
title: "Inschrijving"
author: "de megabike organisatie"
date: '2016-04-17'
url: Inschrijving
---

Beste wielerliefhebber,

Een nieuw voorjaar dient zich aan, dus is het weer tijd voor een nieuwe jaargang megabike (seizoen nr 23), hopelijk terug een seizoen met fantastische wedstrijden!

Het seizoen begint met de Omloop op 28 februari en eindigt op zondag 26 april met Luik-Bastenaken-Luik. Dus het seizoen start iets later dan gewoonlijk.

Op https://jolly-bohr-326994.netlify.app/info/ kan je bekijken welke wedstrijden er meetellen (dat zijn er 17) en kan je ook wat extra informatie opzoeken. De puntentelling voor de renners is geheel gebaseerd op de cqranking te vinden via https://cqranking.com/men/asp/gen/start.asp, indien er een wedstrijd wijzigt van categorie & de info-pagina van megabike is niet meer accuraat, dan is het de puntentelling op cqranking die wordt gebruikt en niet deze die staat op de info-pagina!
De corona-afspraken blijven geldig (& hopelijk overbodig) Megabike gaat door (dus met eindstand) zolang er minimum de helft van de koersen wordt gereden (dat zijn 9 koersen). We wachten eventueel tot maximum het eind van jaar als een koers wordt uitgesteld. Indien megabike stopt krijgen de dagwinnaars hun 6€ uitbetaald, de rest van het geld wordt teruggegeven aan de deelnemers.

Het opzet blijft hetzelfde als de vorige jaren: je selecteert 12 renners voor een maximaal budget van 5000 punten. (Het wordt ook dit jaar nog moeilijker puzzelen, want als je MVDP & Pogacar kiest, dan zit je al 1000 punten over je budget!) Jouw ploeg samenstellen kan het makkelijkst door te puzzelen in de meegezonden excel. Er is ook een pagina met alle renners & hun kost op de website https://jolly-bohr-326994.netlify.app/statistieken/renners/. Als ik een ploeg binnenkrijg bevestig ik altijd met een mailtje terug. (Liefst krijg ik gewoon een lijstje met gekozen renners & zeker hun code, maar de excel terugsturen is eigenlijk nog beter & indien mogelijk in een nieuwe mail, geen reply op een mail van mij.)

Wie extra inspiratie wil, kan eens de statistieken van vorig jaar bekijken, bv kan je op https://jolly-bohr-326994.netlify.app/statistieken/renners-opbrengst/ terecht (en daar sorteren op OpbrengstPercentage). Daar kan je zien wie het meest opbracht vorig jaar tov hun kost. De grote vraag is natuurlijk wie dit jaar de nieuwe Nys wordt…

Het inschrijvingsgeld is zoals vorig jaar 5€. Het is en blijft een eerlijk spel: alle inkomsten worden als prijzengeld terug uitgekeerd. Een dagzege is 6€ waard, dus wie een wedstrijd wint maakt al winst! De rest van de inzet wordt verdeeld tussen de eerste drie in het eindklassement, met de volgende verdeelsleutel: 1/2, 1/3 en 1/6 aan resp. de eerste, tweede en derde.

In geval van een gelijke stand is het de deelnemer met het grootste restbudget die wint. We beperken de inschrijving tot 1 per persoon. (Deze mail mag zeker doorgezonden worden naar andere personen, extra deelnemers zijn zeker welkom, zolang we niet overspoeld worden met nieuwe deelnemers!)
Uw ploeg moet ons bereiken vóór zaterdag 1 maart (dus ten laatste op vrijdag 27 februari, 23u59). Ploegen die ik nadien toegezonden krijg zijn in principe niet geldig. Ik antwoord altijd ter bevestiging dat ik de ploeg goed ontvangen heb.

Betaling van het inschrijvingsgeld van 5€ kan aan Frederik Christiaens, hetzij door persoonlijke overhandiging, hetzij via overschrijving op rek. nr.BE25 6512 2155 5682 op naam van Frederik Christiaens (graag in de mededeling de naam van de deelnemer). Je hebt de tijd tot Nokere Koerse (18 maart) om deze betaling in orde te maken, maar liefst is de betaling al in orde bij de eerste wedstrijd & ik stuur ook herinneringen indien nodig in de eerste week van het seizoen.
Voor vragen en meer info kan je altijd terecht bij Frederik Christiaens per mail.

Sportieve groeten en dat de beste moge winnen!

Arnout, Stijn & Fred