
---
title: "Inschrijving"
author: "de megabike organisatie"
date: '2016-04-17'
url: Inschrijving
---


Beste wielerliefhebber,

Het is alweer februari 2021, VDP heeft ondertussen weer wat crossen gewonnen, men begint hier en daar op exotische plaatsen te koersen, dus tijd voor een nieuw seizoen megabike, dit start dit jaar op 29 februari met de Omloop Het Nieuwsblad.

Al sinds 2004 wordt megabike georganiseerd, eerst door Dries Goossens & Jeroen Belien, ondertussen door mijzelf & Arnout. Dit is dus editie **17!**

Het opzet blijft hetzelfde als de vorige jaren: je selecteert **12 renners** voor een maximaal **budget van 5000 punten**. Vorig jaar was de website wat problematisch, de site ging nu en dan down, dus heb ik er dit jaar voor gekozen om een ander soort site te maken, waardoor ik hem makkelijker gratis ergens kan plaatsen. Nadeel: het is niet meer mogelijk om online je ploeg te selecteren. Voordeel: er is wat meer aandacht voor statistieken allerhande. Bv Er is nu ook een pagina met "Renners-opbrengst", dat toont voor de verschillende megabikejaren het rendement dat werd gehaald punten/kost. (Voor renners met een kost van 0 werd arbitrair 20 gekozen.) Dus in dit lijstje staan de meest interessante renners van het voorbije jaar (of andere jaren als je die selecteert) bovenaan.

Dus je ploeg maken kan dit jaar het makkelijkst door te puzzelen in de meegezonden excel. Er is ook een pagina met alle renners & hun kost op de website indien je liever met pen & papier & zonder excel puzzelt.
Ploegen krijg ik dus graag per mail gezonden, ik bevestig als ik hem gekregen heb. (Liefst gewoon lijstje met gekozen renners & hun **code**, maar excel terugsturen mag ook.)

Het aantal koersen in onze competitie is 17, met dus  nog steeds bv Nokere Koerse, Bredene Koksijde Classic, Eéndaagse Brugge-De Panne,....

Het **inschrijvingsgeld** is zoals vorig jaar **5€**. Het is en blijft een eerlijk spel: alle inkomsten worden als prijzengeld terug uitgekeerd! Een dagzege is**6€** waard**,** dus wie een wedstrijd wint maakt al winst! De rest van de inzet wordt verdeeld tussen de eerste drie in het eindklassement, volgens dezelfde verdeelsleutel als de vorige jaar (1/2, 1/3 en 1/6 aan resp. de eerste, tweede en derde). Vorig jaar met 64 deelnemers was dit respectievelijk +/- 115€, +/- 76,67€ en +/- 38,33€. In geval van een gelijke stand is het de deelnemer met het grootste restbudget die wint. We beperken de inschrijving tot 1 per persoon.

Voor een overzicht van de wedstrijden, de puntentelling, het reglement en andere info verwijzen we graag naar  [http://www.liesmatton.com/megabike/info](http://localhost/megabike/info)

**Uw ploeg moet ons bereiken vóór zaterdag 29 februari (dus ten laatste op vrijdag 28 februari, 23u59).** Ploegen die ik nadien toegezonden krijg zijn in principe niet geldig.

Betaling van het inschrijvingsgeld van **5€** kan aan **Frederik Christiaens**, hetzij door persoonlijke overhandiging, hetzij via overschrijving op rek. nr.**BE11 6511 5490 3548** op naam van Frederik Christiaens (graag in de mededeling de naam van de deelnemer). Je hebt de tijd tot Nokere Koerse (18 maart) om deze betaling in orde te maken.

**Voor vragen en meer info kan je altijd terecht bij** [**frederik.christiaens@gmail.com**](mailto:frederik.christiaens@gmail.com) **.**

Sportieve groeten en dat de beste moge winnen!

Copyright © 2019 megabike
