
---
author: de megabike organisatie
type: post
date: 2020-03-01
categories:
  - Info
title: "Info"
url: "Info"
output: html_document
---

## Regels

Er is een dagprijs (inschrijvingsgeld) om het ook voor diegenen die meteen uit het peloton gelost zullen worden spannend te houden tot de laatste wedstrijd. Ook is er een beperking van maximaal één ploeg per deelnemer. Een samenvatting van de regels:

 - Er tellen 17 wedstrijden mee, namelijk: Omloop Het Nieuwsblad, Kuurne-Brussel-Kuurne, Strade Bianchi, Nokere Koers, Bredene Koksijde Classic, Milaan-Sanremo, Dwars Door Vlaanderen, Eéndaagse Brugge-De Panne, E3 Prijs, Gent-Wevelgem, Ronde Van Vlaanderen, Scheldeprijs, Paris-Roubaix, Brabantse Pijl, Amstel Gold Race, Waalse Pijl, Luik-Bastenaken-Luik. Er zijn verschillende inschalingen voor de wedstrijden met dus verschillende punten, dit kan u verderop lezen.
 - De waarden van de renners hebben we zelf berekend en zijn per renner de gewogen som van de punten behaald in de relevante wedstrijden over de laatste 3 jaar. Punten behaald 3 jaar geleden werden gewogen met een factor 0.8, die van 2 jaar geleden met een factor 1 en die van vorig jaar met 1.2. De rennerslijst vindt u HIER. Wilt u toch een renner selecteren die niet in deze lijst voorkomt? Dit kan op eigen risico en tegen een kost van 0. Zorg wel voor een juiste schrijfwijze, zodat uw organisatoren de renner in kwestie kunnen terugvinden. Je moet nog altijd exact 12 renners selecteren met een maximale totale waarde van 5000! punten.
 - Voor de puntentelling volgen we de officiële CQ-puntentelling. De 17 wedstrijden vallen in 3 categorieën (WT1, WT2, HC) elk met hun eigen puntentelling. Er worden geen punten toegekend aan strijdlustige renners.
 - Wanneer meerdere deelnemers met gelijke punten eindigen, wint degene met het hoogste resterende budget (zowel dagprijs als eindklassement). Indien ook dit gelijk is, wordt het prijzengeld verdeeld over de deelnemers met gelijke punten.

Meerdere ploegen per persoon zijn dus niet toegelaten. Bij inschrijving betaal je 5€, zie voor meer info je email. Inschrijven kan tot middernacht voor de Omloop het Nieuwsblad.

Veel succes aan alle deelnemers en dat de beste moge winnen!!

## Puntentelling
WT1: Milaan-San Remo, Ronde van Vlaanderen, Parijs-Roubaix en Luik-Bastenaken-Luik.
WT2: E3 Prijs Harelbeke, Gent-Wevelgem, Amstel Gold Race en Waalse Pijl.
WT3: Omloop Het Nieuwsblad, Strade Bianche, Dwars door Vlaanderen, Eéndaagse Brugge-De Panne
HC: Kuurne-Brussel-Kuurne, Nokere Koerse, Brabantse Pijl en Scheldeprijs Schoten, Bredene Koksijde Classic

| Rang | WT1 | WT2 | WT3 | HC  |
|------|-----|-----|-----|-----|
| 1    | 280 | 220 | 180 | 130 |
| 2    | 170 | 132 | 108 | 78  |
| 3    | 145 | 112 | 92  | 66  |
| 4    | 125 | 96  | 78  | 58  |
| 5    | 112 | 86  | 70  | 52  |
| 6    | 100 | 76  | 62  | 46  |
| 7    | 90  | 66  | 54  | 40  |
| 8    | 80  | 58  | 46  | 34  |
| 9    | 70  | 52  | 40  | 28  |
| 10   | 62  | 46  | 36  | 24  |
| 11   | 54  | 40  | 30  | 20  |
| 12   | 46  | 35  | 27  | 18  |
| 13   | 42  | 30  | 24  | 16  |
| 14   | 38  | 27  | 22  | 14  |
| 15   | 34  | 24  | 20  | 12  |
| 16   | 32  | 21  | 18  | 10  |
| 17   | 30  | 19  | 16  | 9   |
| 18   | 28  | 18  | 14  | 8   |
| 19   | 26  | 17  | 12  | 7   |
| 20   | 24  | 16  | 11  | 6   |
| 21   | 22  | 15  | 10  | 5   |
| 22   | 20  | 14  | 9   | 5   |
| 23   | 18  | 13  | 8   | 5   |
| 24   | 16  | 12  | 7   | 5   |
| 25   | 14  | 11  | 6   | 5   |
| 26   | 12  | 10  | 5   | 5   |
| 27   | 10  | 9   | 5   | 5   |
| 28   | 8   | 8   | 5   | 5   |
| 29   | 7   | 7   | 5   | 5   |
| 30   | 6   | 6   | 5   | 5   |
| >30* | 5   | 5   |  5  |     |

* Voor wereldbekerwedstrijden (WT1, WT2 & WT3) krijgt elke renner die binnen 5% van de tijd van de winnaar de eindmeet haalt eveneens 5 punten.

## Prijzen
### Dagwinnaar

6€

### Eindwinnaar

De helft van alle overblijvende inschrijvingsgelden (d.i. na aftrek van het prijzengeld voor alle dagwinnaars)

### Tweede in het eindklassement

Eén derde van alle overblijvende inschrijvingsgelden (d.i. na aftrek van het prijzengeld voor alle dagwinnaars)

### Derde in het eindklassement

Eén zesde van alle overblijvende inschrijvingsgelden (d.i. na aftrek van het prijzengeld voor alle dagwinnaars)

## Links
Startlijsten alle wedstrijden:  [CyclingFever](http://www.cyclingfever.com/startlist.html)

Website met onder andere alle uitslagen doorheen het jaar:  [CQ Ranking](http://www.cqranking.com/men/asp/gen/start.asp), voor uitslagen ga naar  [races](http://www.cqranking.com/men/asp/gen/searchRaces.asp).

Wielernieuws: [Cyclingnews](http://www.cyclingnews.com/)

Teams en renners in team:  [cyclingnewsteams](http://www.cyclingnews.com/teams/)
